// file: api_test.go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"github.com/DATA-DOG/godog"
	"github.com/DATA-DOG/godog/gherkin"
)

// record response   //autogenerated code
type apiFeature struct {
	resp *httptest.ResponseRecorder
}
// reset response  //autogenerated code
func (a *apiFeature) resetResponse(interface{}) {
	a.resp = httptest.NewRecorder()
}


// This functions does the "WHEN" clause in feature file eg When I send "POST" request to "/configs"
func (a *apiFeature) iSendrequestTo(method, endpoint string) (err error) {
	req, err := http.NewRequest(method, endpoint, nil)
	if err != nil {
		return
	}

	// handles panic
	defer func() {
		switch t := recover().(type) {
		case string:
			err = fmt.Errorf(t)
		case error:
			err = t
		}
	}()

	// handle url endpoints
	switch endpoint {
	case "/configs":
		// create file if user uses this endpoint
		createFile(a.resp, req)
	default:
		// default is set to be error as there are only some set paths
		err = fmt.Errorf("unknown endpoint: %s", endpoint)
	}
	return
}

// This functions does the "THEN" clause in feature file eg Then the response code should be '405'
func (a *apiFeature) theResponseCodeShouldBe(code int) error {
	if code != a.resp.Code {
		return fmt.Errorf("expected response code to be: %d, but actual is: %d", code, a.resp.Code)
	}
	return nil
}

// This functions does the "AND" clause in the feature file eg And he response should match json: { "apiNamename":"filename"}
func (a *apiFeature) theResponseShouldMatchJSON(body *gherkin.DocString) (err error) {
	var expected, actual []byte
	var data interface{}
	if err = json.Unmarshal([]byte(body.Content), &data); err != nil {
		return
	}
	if expected, err = json.Marshal(data); err != nil {
		return
	}
	actual = a.resp.Body.Bytes()
	if !bytes.Equal(actual, expected) {
		err = fmt.Errorf("expected json, does not match actual: %s", string(actual))
	}
	return
}

// this prints results to command line for users to read
func FeatureContext(s *godog.Suite) {
	api := &apiFeature{}

	s.BeforeScenario(api.resetResponse)

	s.Step(`^I send "(GET|POST|PUT|DELETE)" request to "([^"]*)"$`, api.iSendrequestTo)
	s.Step(`^the response code should be (\d+)$`, api.theResponseCodeShouldBe)
	s.Step(`^the response should match json:$`, api.theResponseShouldMatchJSON)
}